### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by matkoniecz** [Zaczero/Thanos#1]
For now I just looked at readme - but what seems missing is either info how to use it or link to documentation or even mention that people wanting to use it should figure it out from source code

**Comment by Zaczero** [comment]
I sent a video tutorial to https://www.openstreetmap.org/user/Fizzie41. I'll send it to you too. I don't bother writing a HOWTO since this project is intended for use by just a small group of people - I'll mention it in the README.

**Comment by Zaczero** [comment]
https://github.com/Zaczero/Thanos/commit/d9aada78b024287e9e31be9ea01ad432e562d878

Let me know if this resolves the issue :slightly_smiling_face:

**Comment by matkoniecz** [comment]
yep
