### ISSUE TITLE
Would a non-clicky/pointy version be an option?

### ISSUE THREAD

**Issue by SomeoneElseOSM** [Zaczero/Thanos#3]
Something that needs a web browser to interact with is very limited where it can be used.

Something that runs from the command line would be much more flexible - you'd be able to set it going and leave it, and then check on the status afterwards.

**Comment by Zaczero** [comment]
Thanos is a simple Web-UI wrapper around [osm-revert](https://github.com/Zaczero/osm-revert) which is a command-line tool. You can see the revert procedure [here](https://github.com/Zaczero/Thanos/blob/main/revert_worker.py) (like a mass-revert script/logic). And [here](https://github.com/Zaczero/osm-revert/blob/cf18c5318066e7b3c2a51f187574ce6808ee9dda/app/main.py#L128) for all command-line options that are available. One more example of using the tool can be found [here](https://github.com/Zaczero/osm-revert/blob/cf18c5318066e7b3c2a51f187574ce6808ee9dda/web/main.py#L184).

**Comment by SomeoneElseOSM** [comment]
Thanks - I'll have a look at those.

**Comment by Zaczero** [comment]
If you need any help with using it, [send me](https://www.openstreetmap.org/user/NorthCrab) a message on OSM :slightly_smiling_face:. I respond there actively.
