### ISSUE TITLE
On the "Filter changesets" screen the buttons for "Blocked User" and "Deleted account" seem to have no effect

### ISSUE THREAD

**Issue by SomeoneElseOSM** [Zaczero/Thanos#4]
If I click them nothing seems to happen.

**Comment by Zaczero** [comment]
![image](https://github.com/Zaczero/Thanos/assets/10835147/b7d10f16-c241-4a61-9816-6fb6163cff96)

The move buttons below it execute the filters, which include blocked users and deleted accounts in this example. By default, both filters are selected. So, when you click the "Malicious" button above the uncategorized section, you will see the following result:

![image](https://github.com/Zaczero/Thanos/assets/10835147/0943151e-a02b-4c31-9e6f-8ebdf14b7faa)
