### ISSUE TITLE
Ignoring specific nodes etc

### ISSUE THREAD

**Issue by Fizzie41** [Zaczero/Thanos#7]
Have tried to d several reverts e.g. https://thanos.monicz.dev/revert/EAa6mp_-xSNIEC8W2Xvt2Q but they keep getting caught by CS 142945620, with one node: 275296749, that has been massively vandalised: https://osm.mapki.com/history/node/275296749, & which continually comes up as having corrupted data:

Downloading changeset 142945620
[1/?] OpenStreetMap …
[1/2] OpenStreetMap: 1 element
[2/2] Overpass (1 partition) …
[2/2] Partition #1: OK
[2/2] Retrying …
[2/2] Partition #1: OK
❓ Overpass data is corrupted (bad_changeset) (x2)

Is there any way of "ignoring" that node?

**Comment by Zaczero** [comment]
I have [disabled](https://github.com/Zaczero/osm-revert/commit/a64c94184d7f03cdb68595580ae0c3b51a068374) this check in osm-revert for the time being. I'll re-enable it once I've implemented better support for handling multiple changesets at the same time.
